"use client";

import { useEffect, useState, useRef } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowRight,
  Download,
  GitFork,
  BookOpen,
  Shield,
  ChevronDown,
  Flame,
  BarChart3,
  Zap,
  Lock,
  Star,
  CheckCircle2,
  KeyRound,
  Database,
  Cpu,
  Sparkles,
  Terminal,
} from "lucide-react";
import { supabaseAuth } from "../services/supabaseAuth";
import PublicNavbar from "../components/PublicNavbar";
import { gsap } from "gsap";

/* Animated Counter */
function Counter({ to, suffix = "" }: { to: number; suffix?: string }) {
  const [val, setVal] = useState(0);
  const ref = useRef<HTMLSpanElement>(null);
  const started = useRef(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started.current) {
          started.current = true;
          let s = 0;
          const step = to / 50;
          const id = setInterval(() => {
            s += step;
            if (s >= to) {
              setVal(to);
              clearInterval(id);
            } else setVal(Math.floor(s));
          }, 20);
        }
      },
      { threshold: 0.5 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [to]);
  return <span ref={ref}>{val}{suffix}</span>;
}

/* Sample Code Snippets for Interactive Hero Tabs - Light Theme Syntax */
const CODE_SAMPLES: Record<string, { file: string; lang: string; runtime: string; memory: string; code: React.ReactNode }> = {
  python: {
    file: "my-leetcode-vault/easy/0001-two-sum/solution.py",
    lang: "Python 3",
    runtime: "48 ms (Top 88%)",
    memory: "17.2 MB",
    code: (
      <>
        <div style={{ color: "#94a3b8", marginBottom: 12 }}># Auto-generated by CodeVault on 2026-07-25</div>
        <div><span style={{ color: "#635bff", fontWeight: 700 }}>class</span> <span style={{ color: "#0284c7", fontWeight: 700 }}>Solution</span>:</div>
        <div style={{ paddingLeft: 16 }}><span style={{ color: "#635bff", fontWeight: 700 }}>def</span> <span style={{ color: "#0284c7", fontWeight: 700 }}>twoSum</span>(self, nums: List[int], target: int) -&gt; List[int]:</div>
        <div style={{ paddingLeft: 32, color: "#475569" }}>seen = &#123;&#125;</div>
        <div style={{ paddingLeft: 32 }}><span style={{ color: "#635bff", fontWeight: 700 }}>for</span> <span style={{ color: "#0f172a" }}>i, n</span> <span style={{ color: "#635bff", fontWeight: 700 }}>in</span> <span style={{ color: "#0284c7" }}>enumerate</span>(nums):</div>
        <div style={{ paddingLeft: 48 }}><span style={{ color: "#635bff", fontWeight: 700 }}>if</span> <span style={{ color: "#0f172a" }}>target - n</span> <span style={{ color: "#635bff", fontWeight: 700 }}>in</span> <span style={{ color: "#0f172a" }}>seen</span>:</div>
        <div style={{ paddingLeft: 64 }}><span style={{ color: "#635bff", fontWeight: 700 }}>return</span> <span style={{ color: "#059669", fontWeight: 600 }}>[seen[target - n], i]</span></div>
        <div style={{ paddingLeft: 48, color: "#475569" }}>seen[n] = i</div>
      </>
    ),
  },
  cpp: {
    file: "my-leetcode-vault/medium/0002-add-two-numbers/solution.cpp",
    lang: "C++",
    runtime: "12 ms (Top 94%)",
    memory: "71.4 MB",
    code: (
      <>
        <div style={{ color: "#94a3b8", marginBottom: 12 }}>// Auto-generated by CodeVault on 2026-07-25</div>
        <div><span style={{ color: "#635bff", fontWeight: 700 }}>class</span> <span style={{ color: "#0284c7", fontWeight: 700 }}>Solution</span> &#123;</div>
        <div><span style={{ color: "#635bff", fontWeight: 700 }}>public</span>:</div>
        <div style={{ paddingLeft: 16 }}>ListNode* <span style={{ color: "#0284c7", fontWeight: 700 }}>addTwoNumbers</span>(ListNode* l1, ListNode* l2) &#123;</div>
        <div style={{ paddingLeft: 32, color: "#0f172a" }}>ListNode dummy(0); ListNode* tail = &amp;dummy;</div>
        <div style={{ paddingLeft: 32, color: "#0f172a" }}>int carry = 0;</div>
        <div style={{ paddingLeft: 32 }}><span style={{ color: "#635bff", fontWeight: 700 }}>while</span> <span style={{ color: "#0f172a" }}>(l1 || l2 || carry)</span> &#123;</div>
        <div style={{ paddingLeft: 48, color: "#0f172a" }}>int sum = (l1 ? l1-&gt;val : 0) + (l2 ? l2-&gt;val : 0) + carry;</div>
        <div style={{ paddingLeft: 48, color: "#0f172a" }}>carry = sum / 10;</div>
        <div style={{ paddingLeft: 48, color: "#0f172a" }}>tail-&gt;next = new ListNode(sum % 10);</div>
        <div style={{ paddingLeft: 48, color: "#0f172a" }}>tail = tail-&gt;next;</div>
        <div style={{ paddingLeft: 32 }}>&#125;</div>
        <div style={{ paddingLeft: 32 }}><span style={{ color: "#635bff", fontWeight: 700 }}>return</span> <span style={{ color: "#059669", fontWeight: 600 }}>dummy.next;</span></div>
        <div style={{ paddingLeft: 16 }}>&#125;</div>
        <div>&#125;;</div>
      </>
    ),
  },
  typescript: {
    file: "my-leetcode-vault/hard/0004-median-arrays/solution.ts",
    lang: "TypeScript",
    runtime: "84 ms (Top 91%)",
    memory: "46.8 MB",
    code: (
      <>
        <div style={{ color: "#94a3b8", marginBottom: 12 }}>// Auto-generated by CodeVault on 2026-07-25</div>
        <div><span style={{ color: "#635bff", fontWeight: 700 }}>function</span> <span style={{ color: "#0284c7", fontWeight: 700 }}>findMedianSortedArrays</span>(nums1: number[], nums2: number[]): number &#123;</div>
        <div style={{ paddingLeft: 16, color: "#0f172a" }}>const merged = [...nums1, ...nums2].sort((a, b) =&gt; a - b);</div>
        <div style={{ paddingLeft: 16, color: "#0f172a" }}>const mid = Math.floor(merged.length / 2);</div>
        <div style={{ paddingLeft: 16 }}><span style={{ color: "#635bff", fontWeight: 700 }}>return</span> <span style={{ color: "#0f172a" }}>merged.length % 2 !== 0</span></div>
        <div style={{ paddingLeft: 32, color: "#059669", fontWeight: 600 }}>? merged[mid]</div>
        <div style={{ paddingLeft: 32, color: "#059669", fontWeight: 600 }}>: (merged[mid - 1] + merged[mid]) / 2;</div>
        <div>&#125;</div>
      </>
    ),
  },
};

export default function LandingPage() {
  const router = useRouter();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(0);
  const [activeLang, setActiveLang] = useState<"python" | "cpp" | "typescript">("python");
  const [scrolled, setScrolled] = useState(false);

  // GSAP Refs
  const heroBadgeRef = useRef<HTMLDivElement>(null);
  const heroHeadlineRef = useRef<HTMLHeadingElement>(null);
  const heroSubRef = useRef<HTMLParagraphElement>(null);
  const heroCtaRef = useRef<HTMLDivElement>(null);
  const heroTrustRef = useRef<HTMLDivElement>(null);
  const ideShowcaseRef = useRef<HTMLDivElement>(null);
  const heroGlowRef = useRef<HTMLDivElement>(null);
  const codePanelRef = useRef<HTMLDivElement>(null);

  const featuresGridRef = useRef<HTMLDivElement>(null);
  const stepsGridRef = useRef<HTMLDivElement>(null);
  const architectureRef = useRef<HTMLDivElement>(null);
  const directoryTreeRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setIsAuthenticated(Boolean(supabaseAuth.getSession()));
  }, []);

  useEffect(() => {
    const h = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", h);
    return () => window.removeEventListener("scroll", h);
  }, []);

  const go = () => router.push(isAuthenticated ? "/dashboard" : "/login");

  // GSAP Hero Entrance Timeline & Ambient Glow Loop
  useEffect(() => {
    const ctx = gsap.context(() => {
      const tl = gsap.timeline({ defaults: { ease: "power3.out" } });

      if (heroBadgeRef.current) {
        tl.fromTo(
          heroBadgeRef.current,
          { opacity: 0, y: -20, scale: 0.9 },
          { opacity: 1, y: 0, scale: 1, duration: 0.5, ease: "back.out(1.7)" }
        );
      }

      if (heroHeadlineRef.current) {
        tl.fromTo(
          heroHeadlineRef.current,
          { opacity: 0, y: 30 },
          { opacity: 1, y: 0, duration: 0.7 },
          "-=0.3"
        );
      }

      if (heroSubRef.current) {
        tl.fromTo(
          heroSubRef.current,
          { opacity: 0, y: 20 },
          { opacity: 1, y: 0, duration: 0.5 },
          "-=0.4"
        );
      }

      if (heroCtaRef.current && heroCtaRef.current.children) {
        tl.fromTo(
          Array.from(heroCtaRef.current.children),
          { opacity: 0, y: 20, scale: 0.95 },
          { opacity: 1, y: 0, scale: 1, duration: 0.5, stagger: 0.1, ease: "back.out(1.4)" },
          "-=0.3"
        );
      }

      if (heroTrustRef.current && heroTrustRef.current.children) {
        tl.fromTo(
          Array.from(heroTrustRef.current.children),
          { opacity: 0, y: 15 },
          { opacity: 1, y: 0, duration: 0.4, stagger: 0.08 },
          "-=0.2"
        );
      }

      if (ideShowcaseRef.current) {
        tl.fromTo(
          ideShowcaseRef.current,
          { opacity: 0, y: 50, rotateX: 6 },
          { opacity: 1, y: 0, rotateX: 0, duration: 0.9, ease: "power4.out" },
          "-=0.4"
        );
      }

      // Ambient Breathing Glow Loop
      if (heroGlowRef.current) {
        gsap.to(heroGlowRef.current, {
          x: "random(-40, 40)",
          y: "random(-30, 30)",
          scale: 1.12,
          duration: 6,
          repeat: -1,
          yoyo: true,
          ease: "sine.inOut",
        });
      }
    });

    return () => ctx.revert();
  }, []);

  // GSAP Code Tab Transition Effect
  useEffect(() => {
    if (codePanelRef.current) {
      gsap.fromTo(
        codePanelRef.current,
        { opacity: 0, y: 8, scale: 0.99 },
        { opacity: 1, y: 0, scale: 1, duration: 0.3, ease: "power3.out" }
      );
    }
  }, [activeLang]);

  // Scroll Reveal Observer for Features Grid
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting && featuresGridRef.current) {
            gsap.fromTo(
              Array.from(featuresGridRef.current.children),
              { opacity: 0, y: 35, scale: 0.95 },
              { opacity: 1, y: 0, scale: 1, duration: 0.6, stagger: 0.08, ease: "back.out(1.2)" }
            );
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.15 }
    );

    if (featuresGridRef.current) observer.observe(featuresGridRef.current);
    return () => observer.disconnect();
  }, []);

  // Scroll Reveal Observer for Steps Grid
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting && stepsGridRef.current) {
            gsap.fromTo(
              Array.from(stepsGridRef.current.children),
              { opacity: 0, y: 40, x: -10 },
              { opacity: 1, y: 0, x: 0, duration: 0.6, stagger: 0.12, ease: "power3.out" }
            );
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.15 }
    );

    if (stepsGridRef.current) observer.observe(stepsGridRef.current);
    return () => observer.disconnect();
  }, []);

  // Scroll Reveal Observer for Architecture Section
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            if (architectureRef.current) {
              gsap.fromTo(
                architectureRef.current,
                { opacity: 0, x: -40 },
                { opacity: 1, x: 0, duration: 0.7, ease: "power3.out" }
              );
            }
            if (directoryTreeRef.current) {
              gsap.fromTo(
                directoryTreeRef.current,
                { opacity: 0, x: 40, scale: 0.96 },
                { opacity: 1, x: 0, scale: 1, duration: 0.7, ease: "power3.out", delay: 0.15 }
              );
            }
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.15 }
    );

    if (architectureRef.current) observer.observe(architectureRef.current);
    return () => observer.disconnect();
  }, []);

  // 3D Parallax Mouse Tracking on IDE Showcase
  const handleIdeMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!ideShowcaseRef.current) return;
    const rect = ideShowcaseRef.current.getBoundingClientRect();
    const x = (e.clientX - rect.left) / rect.width - 0.5;
    const y = (e.clientY - rect.top) / rect.height - 0.5;
    gsap.to(ideShowcaseRef.current, {
      rotateY: x * 6,
      rotateX: -y * 6,
      duration: 0.4,
      ease: "power2.out",
    });
  };

  const handleIdeMouseLeave = () => {
    if (!ideShowcaseRef.current) return;
    gsap.to(ideShowcaseRef.current, {
      rotateY: 0,
      rotateX: 0,
      duration: 0.8,
      ease: "power2.out",
    });
  };

  // Magnetic Button Hover helper
  const handleMagneticMove = (e: React.MouseEvent<HTMLElement>, intensity = 0.2) => {
    const btn = e.currentTarget;
    const rect = btn.getBoundingClientRect();
    const x = e.clientX - rect.left - rect.width / 2;
    const y = e.clientY - rect.top - rect.height / 2;
    gsap.to(btn, { x: x * intensity, y: y * intensity, duration: 0.2, ease: "power2.out" });
  };

  const handleMagneticLeave = (e: React.MouseEvent<HTMLElement>) => {
    gsap.to(e.currentTarget, { x: 0, y: 0, duration: 0.5, ease: "elastic.out(1, 0.4)" });
  };

  const faqs = [
    {
      q: "How does CodeVault authenticate with my GitHub account?",
      a: "CodeVault uses a Personal Access Token (PAT) provided during onboarding. Your token is encrypted at rest using AES-256 and used strictly to execute commits via the GitHub Contents API. No account password access is ever required.",
    },
    {
      q: "Can I target a private GitHub repository?",
      a: "Yes. CodeVault supports both public and private repositories seamlessly. You select visibility during repository configuration.",
    },
    {
      q: "Does the Chrome extension consume system resources?",
      a: "No. The extension operates as an event-driven Manifest V3 service worker. It remains idle until an accepted LeetCode submission is detected, ensuring zero background CPU or memory footprint.",
    },
    {
      q: "Which programming languages are supported?",
      a: "All major LeetCode languages are supported — including Python, C++, Java, JavaScript, TypeScript, Rust, Go, C#, Swift, Kotlin, and SQL — committed with standardized file extensions and folder structures.",
    },
    {
      q: "Where is my source code stored?",
      a: "Your solution code is committed directly from your browser to your GitHub repository. CodeVault servers store only basic profile and repository configuration metadata.",
    },
  ];

  const features = [
    {
      icon: Shield,
      title: "Encrypted PAT Bridge",
      desc: "OAuth-safe authentication architecture. Your GitHub Personal Access Token is encrypted at rest using AES-256.",
    },
    {
      icon: Zap,
      title: "Real-Time Auto-Commit",
      desc: "Solutions are parsed, documented, and committed to your repository the exact second your submission is accepted.",
    },
    {
      icon: BarChart3,
      title: "Repository Analytics",
      desc: "Track practice velocity, difficulty distribution, language ratios, and streaks generated from your vault.",
    },
    {
      icon: GitFork,
      title: "Standardized Vault Layout",
      desc: "Clean directory hierarchy with difficulty subfolders (easy/medium/hard), solution source code, and problem READMEs.",
    },
    {
      icon: Flame,
      title: "Streak & Activity Tracking",
      desc: "Maintain practice momentum with calendar heatmaps and activity counters calculated from your commit history.",
    },
    {
      icon: BookOpen,
      title: "Developer Documentation",
      desc: "Comprehensive integration guides covering extension installation, token scoping, API reference, and architecture.",
    },
  ];

  const steps = [
    {
      num: "01",
      title: "Install Extension",
      desc: "Download CodeVault.zip and load unpacked in chrome://extensions in 30 seconds.",
    },
    {
      num: "02",
      title: "Sign In",
      desc: "Create an account. The extension automatically detects your active web session.",
    },
    {
      num: "03",
      title: "Bind Repository",
      desc: "Connect your target GitHub repository and Personal Access Token in the wizard.",
    },
    {
      num: "04",
      title: "Solve & Sync",
      desc: "Solve on LeetCode. Accepted solutions are committed and structured automatically.",
    },
  ];

  const sampleSample = CODE_SAMPLES[activeLang];

  return (
    <div style={{ background: "#ffffff", color: "#0f172a", minHeight: "100vh", fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", overflowX: "hidden" }}>

      {/* ── NAVIGATION ─────────────────────────── */}
      <PublicNavbar />

      {/* ── HERO SECTION ───────────────────────── */}
      <section className="responsive-hero-section" style={{ paddingTop: 148, paddingBottom: 88, paddingLeft: 48, paddingRight: 48, textAlign: "center", position: "relative", background: "#ffffff", perspective: 1000 }}>

        {/* GSAP Animated Background Ambient Glow */}
        <div
          ref={heroGlowRef}
          style={{
            position: "absolute", top: "25%", left: "50%", transform: "translate(-50%, -50%)",
            width: 720, height: 460, borderRadius: "50%",
            background: "radial-gradient(circle, rgba(99, 91, 255, 0.22) 0%, rgba(168, 85, 247, 0.09) 50%, transparent 75%)",
            pointerEvents: "none", zIndex: 0, filter: "blur(20px)"
          }}
        />

        {/* Subtle grid background */}
        <div style={{
          position: "absolute", inset: 0, zIndex: 0, pointerEvents: "none",
          backgroundImage: "linear-gradient(#f1f5f9 1px, transparent 1px), linear-gradient(90deg, #f1f5f9 1px, transparent 1px)",
          backgroundSize: "40px 40px", opacity: 0.6
        }} />

        <div style={{ maxWidth: 840, margin: "0 auto", position: "relative", zIndex: 1 }}>

          {/* Pill Badge with Pulsing Light */}
          <div
            ref={heroBadgeRef}
            style={{
              display: "inline-flex", alignItems: "center", gap: 8,
              background: "#f8fafc", border: "1px solid #e2e8f0",
              borderRadius: 100, padding: "6px 16px", fontSize: 12, fontWeight: 600, color: "#475569",
              marginBottom: 32, boxShadow: "0 2px 8px rgba(99,91,255,0.06)"
            }}
          >
            <span style={{ width: 7, height: 7, borderRadius: "50%", background: "#635bff", display: "inline-block", boxShadow: "0 0 8px #635bff" }} />
            <span>Developer Tool · Chrome Extension Manifest V3</span>
            <Sparkles size={13} style={{ color: "#a855f7" }} />
          </div>

          {/* H1 Headline with Vibrant Gradient Wordmark */}
          <h1
            ref={heroHeadlineRef}
            style={{
              fontSize: "clamp(40px, 5.5vw, 64px)", fontWeight: 800,
              letterSpacing: "-0.04em", lineHeight: 1.1, margin: "0 0 24px", color: "#0f172a"
            }}
          >
            Automate your LeetCode<br />
            <span style={{
              background: "linear-gradient(135deg, #635bff 0%, #a855f7 100%)",
              WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent"
            }}>
              repository on GitHub.
            </span>
          </h1>

          {/* Subtitle */}
          <p
            ref={heroSubRef}
            style={{
              fontSize: "clamp(16px, 1.8vw, 18px)", color: "#475569",
              maxWidth: 620, margin: "0 auto 40px", lineHeight: 1.6, fontWeight: 400
            }}
          >
            CodeVault bridges LeetCode and GitHub in real time. Accepted submissions are structured, documented, and committed to your personal repository automatically.
          </p>

          {/* CTA Buttons with GSAP Magnetic Effect */}
          <div ref={heroCtaRef} style={{ display: "flex", justifyContent: "center", gap: 14, flexWrap: "wrap", alignItems: "center" }}>
            <button
              onClick={go}
              onMouseMove={(e) => handleMagneticMove(e, 0.2)}
              onMouseLeave={handleMagneticLeave}
              style={{
                background: "#635bff", color: "#ffffff", padding: "14px 30px", fontSize: 15, fontWeight: 600,
                borderRadius: 10, border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 8,
                transition: "background 0.15s ease, box-shadow 0.2s", boxShadow: "0 4px 16px rgba(99,91,255,0.3)"
              }}
              onMouseEnter={e => { e.currentTarget.style.background = "#4f46e5"; }}
            >
              Start Free Account <ArrowRight size={16} />
            </button>

            <div>
              <Link
                href="/download"
                onMouseMove={(e) => handleMagneticMove(e, 0.2)}
                onMouseLeave={handleMagneticLeave}
                style={{
                  background: "#ffffff", color: "#0f172a", padding: "14px 26px", fontSize: 15, fontWeight: 600,
                  borderRadius: 10, border: "1px solid #cbd5e1",
                  display: "flex", alignItems: "center", gap: 8, textDecoration: "none",
                  transition: "border-color 0.15s, background 0.15s"
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = "#635bff"; }}
              >
                <Download size={16} /> Download Extension
              </Link>
            </div>
          </div>

          {/* Trust Badges */}
          <div ref={heroTrustRef} style={{ marginTop: 40, display: "flex", justifyContent: "center", gap: 32, flexWrap: "wrap" }}>
            {[
              { label: "Free for individual developers" },
              { label: "Zero source code on our servers" },
              { label: "10+ programming languages" },
            ].map((item, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "#64748b", fontWeight: 500 }}>
                <CheckCircle2 size={14} style={{ color: "#635bff" }} />
                <span>{item.label}</span>
              </div>
            ))}
          </div>

        </div>

        {/* ── IDE SHOWCASE WITH GSAP 3D TILT & PARALLAX ── */}
        <div
          ref={ideShowcaseRef}
          onMouseMove={handleIdeMouseMove}
          onMouseLeave={handleIdeMouseLeave}
          style={{
            maxWidth: 960, margin: "64px auto 0", position: "relative", zIndex: 1,
            transformStyle: "preserve-3d", transition: "box-shadow 0.3s"
          }}
        >
          <div style={{
            background: "#ffffff", border: "1.5px solid #e2e8f0",
            borderRadius: 16, boxShadow: "0 20px 50px -10px rgba(99, 91, 255, 0.12), 0 4px 16px rgba(15, 23, 42, 0.04)",
            overflow: "hidden", textAlign: "left"
          }}>
            {/* Window Topbar */}
            <div style={{ padding: "10px 20px", background: "#f8fafc", borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#fca5a5" }} />
                <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#fde68a" }} />
                <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#86efac" }} />
                <span style={{ marginLeft: 12, fontSize: 12, color: "#64748b", fontWeight: 600, fontFamily: "monospace" }}>
                  {sampleSample.file}
                </span>
              </div>

              {/* Language Switcher Tabs */}
              <div style={{ display: "flex", gap: 4, background: "#e2e8f0", padding: 3, borderRadius: 8 }}>
                {(["python", "cpp", "typescript"] as const).map(l => (
                  <button
                    key={l}
                    onClick={() => setActiveLang(l)}
                    style={{
                      padding: "4px 12px", fontSize: 12, fontWeight: 700, borderRadius: 6, border: "none", cursor: "pointer",
                      background: activeLang === l ? "#ffffff" : "transparent",
                      color: activeLang === l ? "#635bff" : "#64748b",
                      boxShadow: activeLang === l ? "0 1px 3px rgba(0,0,0,0.1)" : "none",
                      transition: "all 0.15s",
                    }}>
                    {l === "python" ? "Python 3" : l === "cpp" ? "C++" : "TypeScript"}
                  </button>
                ))}
              </div>
            </div>

            {/* Split Code View */}
            <div className="responsive-grid-1col" style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr", background: "#fafbfe" }}>
              {/* Code Panel with GSAP Animated Tab Switch */}
              <div
                ref={codePanelRef}
                style={{ padding: "24px", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 13, color: "#0f172a", lineHeight: 1.6, borderRight: "1px solid #e2e8f0", minHeight: 220, background: "#ffffff" }}
              >
                {sampleSample.code}
              </div>

              {/* Commit Meta Panel */}
              <div style={{ padding: "24px", background: "#f4f3ff", color: "#0f172a", display: "flex", flexDirection: "column", justifyContent: "space-between", borderLeft: "1px solid #ede9fe" }}>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#635bff", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8 }}>Commit Metadata</div>
                  <div style={{ fontSize: 14, fontWeight: 800, color: "#0f172a", marginBottom: 16 }}>feat: add {sampleSample.file.split("/")[2].split("-").slice(1).join(" ")} solution</div>

                  <div style={{ display: "flex", flexDirection: "column", gap: 10, fontSize: 12, color: "#475569" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #ede9fe", paddingBottom: 6 }}>
                      <span>Difficulty:</span> <span style={{ color: "#059669", fontWeight: 700 }}>{sampleSample.file.split("/")[1].toUpperCase()}</span>
                    </div>
                    <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #ede9fe", paddingBottom: 6 }}>
                      <span>Language:</span> <span style={{ fontWeight: 700, color: "#635bff" }}>{sampleSample.lang}</span>
                    </div>
                    <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #ede9fe", paddingBottom: 6 }}>
                      <span>Runtime:</span> <span style={{ fontWeight: 600 }}>{sampleSample.runtime}</span>
                    </div>
                    <div style={{ display: "flex", justifyContent: "space-between" }}>
                      <span>Memory:</span> <span style={{ fontWeight: 600 }}>{sampleSample.memory}</span>
                    </div>
                  </div>
                </div>

                <div style={{ padding: "12px", background: "#ffffff", borderRadius: 8, border: "1px solid #ede9fe", fontSize: 12, color: "#059669", fontWeight: 600 }}>
                  ✓ README.md and stats.json updated automatically.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── METRICS STRIP ───────────────────────── */}
      <section className="responsive-hero-section" style={{ padding: "48px", background: "#f8fafc", borderTop: "1px solid #e2e8f0", borderBottom: "1px solid #e2e8f0" }}>
        <div className="responsive-grid-2col" style={{ maxWidth: 960, margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 32, textAlign: "center" }}>
          {[
            { val: 2400, suffix: "+", label: "Active Developers" },
            { val: 50, suffix: "K+", label: "Commits Synced" },
            { val: 10, suffix: "+", label: "Languages" },
            { val: 100, suffix: "%", label: "Free & Open Source" },
          ].map((s, i) => (
            <div key={i}>
              <div style={{ fontSize: 36, fontWeight: 800, color: "#0f172a", letterSpacing: "-0.03em", marginBottom: 4 }}>
                <Counter to={s.val} suffix={s.suffix} />
              </div>
              <div style={{ fontSize: 13, color: "#64748b", fontWeight: 500 }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── FEATURES GRID WITH GSAP SCROLL REVEAL ─────── */}
      <section id="features" className="responsive-hero-section" style={{ padding: "96px 48px", background: "#ffffff" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div style={{ textAlign: "center", marginBottom: 64 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#635bff", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 12 }}>
              Capabilities
            </div>
            <h2 style={{ fontSize: "clamp(28px, 3.5vw, 40px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#0f172a", margin: "0 0 14px" }}>
              Engineered for developer workflows
            </h2>
            <p style={{ fontSize: 16, color: "#64748b", maxWidth: 520, margin: "0 auto", lineHeight: 1.6 }}>
              A robust synchronization platform for software engineers who value clean revision histories and data ownership.
            </p>
          </div>

          <div
            ref={featuresGridRef}
            className="responsive-grid-1col"
            style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 24 }}
          >
            {features.map((f, i) => (
              <div
                key={i}
                onMouseMove={(e) => handleMagneticMove(e, 0.08)}
                onMouseLeave={handleMagneticLeave}
                style={{
                  padding: "32px 28px", borderRadius: 12, background: "#ffffff",
                  border: "1px solid #e2e8f0", transition: "border-color 0.2s, box-shadow 0.2s", cursor: "default"
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = "#635bff"; e.currentTarget.style.boxShadow = "0 14px 32px -6px rgba(99, 91, 255, 0.12)"; }}
              >
                <div style={{ width: 42, height: 42, borderRadius: 8, background: "#f4f3ff", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 20 }}>
                  <f.icon size={20} style={{ color: "#635bff" }} />
                </div>
                <h3 style={{ fontSize: 16, fontWeight: 700, margin: "0 0 10px", color: "#0f172a" }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: "#64748b", margin: 0, lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECURITY & ARCHITECTURE SECTION ────── */}
      <section id="architecture" className="responsive-hero-section" style={{ padding: "96px 48px", background: "#f8fafc", borderTop: "1px solid #e2e8f0", borderBottom: "1px solid #e2e8f0" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div className="responsive-grid-1col" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 48, alignItems: "center" }}>
            <div ref={architectureRef}>
              <div style={{ fontSize: 12, fontWeight: 700, color: "#635bff", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 12 }}>
                Trust &amp; Security Architecture
              </div>
              <h2 style={{ fontSize: "clamp(28px, 3.5vw, 40px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#0f172a", margin: "0 0 18px", lineHeight: 1.2 }}>
                Zero code retention. Direct-to-GitHub pipeline.
              </h2>
              <p style={{ fontSize: 16, color: "#475569", lineHeight: 1.7, margin: "0 0 28px" }}>
                CodeVault separates platform identity from solution data. Your source code goes straight from your browser extension to your personal GitHub repository — never stored on our database.
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
                {[
                  { icon: KeyRound, title: "AES-256 PAT Encryption", desc: "Personal Access Tokens are stored encrypted in Supabase using Row Level Security (RLS)." },
                  { icon: Cpu, title: "Local Offline Queue", desc: "If your network drops, solutions are enqueued locally in chrome.storage until connection returns." },
                  { icon: Database, title: "Zero Password Exposure", desc: "Extension inherits web authentication via Supabase Auth — no raw passwords inside extension." },
                ].map((sec, idx) => (
                  <div key={idx} style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
                    <div style={{ width: 36, height: 36, borderRadius: 8, background: "#f4f3ff", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                      <sec.icon size={18} style={{ color: "#635bff" }} />
                    </div>
                    <div>
                      <div style={{ fontSize: 15, fontWeight: 700, color: "#0f172a" }}>{sec.title}</div>
                      <div style={{ fontSize: 13, color: "#64748b", lineHeight: 1.5, marginTop: 2 }}>{sec.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Visual Vault Directory Tree Card */}
            <div
              ref={directoryTreeRef}
              onMouseMove={(e) => handleMagneticMove(e, 0.08)}
              onMouseLeave={handleMagneticLeave}
              style={{ background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 16, padding: "28px", boxShadow: "0 10px 30px rgba(15, 23, 42, 0.05)", transition: "border-color 0.2s" }}
            >
              <div style={{ fontSize: 12, fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 16 }}>
                Automated Repository Directory Layout
              </div>
              <div style={{ fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 13, color: "#334155", lineHeight: 1.8 }}>
                <div style={{ fontWeight: 700, color: "#635bff" }}>📁 my-leetcode-vault/</div>
                <div style={{ paddingLeft: 18 }}>├── 📁 easy/</div>
                <div style={{ paddingLeft: 36 }}>└── 📁 0001-two-sum/</div>
                <div style={{ paddingLeft: 54, color: "#059669" }}>├── 📄 solution.py</div>
                <div style={{ paddingLeft: 54, color: "#64748b" }}>├── 📄 README.md</div>
                <div style={{ paddingLeft: 54, color: "#64748b" }}>└── 📄 metadata.json</div>
                <div style={{ paddingLeft: 18 }}>├── 📁 medium/</div>
                <div style={{ paddingLeft: 36 }}>└── 📁 0002-add-two-numbers/</div>
                <div style={{ paddingLeft: 18 }}>├── 📁 hard/</div>
                <div style={{ paddingLeft: 18, color: "#7c3aed", fontWeight: 700 }}>├── 📄 stats.json</div>
                <div style={{ paddingLeft: 18, color: "#7c3aed", fontWeight: 700 }}>└── 📄 README.md</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ───────────────────────── */}
      <section id="how-it-works" className="responsive-hero-section" style={{ padding: "96px 48px", background: "#ffffff" }}>
        <div style={{ maxWidth: 1040, margin: "0 auto" }}>
          <div style={{ textAlign: "center", marginBottom: 64 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#635bff", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 12 }}>
              Integration Workflow
            </div>
            <h2 style={{ fontSize: "clamp(28px, 3.5vw, 40px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#0f172a", margin: "0 0 14px" }}>
              Four steps to continuous synchronization
            </h2>
            <p style={{ fontSize: 16, color: "#64748b", maxWidth: 480, margin: "0 auto", lineHeight: 1.6 }}>
              Zero manual file exports. Seamless background pipeline.
            </p>
          </div>

          <div
            ref={stepsGridRef}
            className="responsive-grid-1col"
            style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16 }}
          >
            {steps.map((s, i) => (
              <div
                key={i}
                onMouseMove={(e) => handleMagneticMove(e, 0.08)}
                onMouseLeave={handleMagneticLeave}
                style={{
                  padding: "32px 24px", background: "#ffffff", border: "1px solid #e2e8f0",
                  borderRadius: 12, transition: "border-color 0.2s, box-shadow 0.2s"
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = "#635bff"; e.currentTarget.style.boxShadow = "0 8px 24px rgba(99,91,255,0.08)"; }}
              >
                <div style={{
                  fontSize: 12, fontWeight: 800, color: "#635bff", background: "#f4f3ff",
                  padding: "4px 10px", borderRadius: 6, display: "inline-block", marginBottom: 20
                }}>
                  STEP {s.num}
                </div>
                <h3 style={{ fontSize: 15, fontWeight: 700, margin: "0 0 10px", color: "#0f172a" }}>{s.title}</h3>
                <p style={{ fontSize: 13, color: "#64748b", margin: 0, lineHeight: 1.6 }}>{s.desc}</p>
              </div>
            ))}
          </div>

          <div style={{ textAlign: "center", marginTop: 48 }}>
            <button
              onClick={go}
              onMouseMove={(e) => handleMagneticMove(e, 0.2)}
              onMouseLeave={handleMagneticLeave}
              style={{
                background: "#635bff", color: "#ffffff", padding: "12px 28px", fontSize: 14, fontWeight: 600,
                borderRadius: 8, border: "none", cursor: "pointer", display: "inline-flex",
                alignItems: "center", gap: 8, transition: "background 0.15s, box-shadow 0.2s",
                boxShadow: "0 4px 16px rgba(99,91,255,0.25)"
              }}
              onMouseEnter={e => { e.currentTarget.style.background = "#4f46e5"; }}
            >
              Get Started Free <ArrowRight size={16} />
            </button>
          </div>
        </div>
      </section>

      {/* ── FAQ SECTION ────────────────────────── */}
      <section id="faq" className="responsive-hero-section" style={{ padding: "96px 48px", background: "#f8fafc", borderTop: "1px solid #e2e8f0", borderBottom: "1px solid #e2e8f0" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <div style={{ textAlign: "center", marginBottom: 64 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: "#635bff", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 12 }}>
              Questions &amp; Answers
            </div>
            <h2 style={{ fontSize: "clamp(28px, 3.5vw, 40px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#0f172a", margin: 0 }}>
              Frequently Asked Questions
            </h2>
          </div>

          <div style={{ display: "flex", flexDirection: "column" }}>
            {faqs.map((faq, idx) => (
              <div key={idx} style={{ borderBottom: "1px solid #e2e8f0", background: "#ffffff", marginBottom: 8, borderRadius: 8, padding: "16px 20px" }}>
                <button onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                  style={{ width: "100%", background: "none", border: 0, textAlign: "left", display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer", gap: 16 }}>
                  <span style={{ fontSize: 15, fontWeight: 700, color: "#0f172a", lineHeight: 1.4 }}>{faq.q}</span>
                  <motion.div animate={{ rotate: activeFaq === idx ? 180 : 0 }} transition={{ duration: 0.2 }}>
                    <ChevronDown size={16} style={{ color: "#64748b" }} />
                  </motion.div>
                </button>
                <AnimatePresence>
                  {activeFaq === idx && (
                    <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25, ease: "easeInOut" }}>
                      <p style={{ fontSize: 14, color: "#64748b", lineHeight: 1.7, margin: "12px 0 0", paddingRight: 32 }}>{faq.a}</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>

          <div style={{ textAlign: "center", marginTop: 44 }}>
            <Link
              href="/faq"
              onMouseMove={(e) => handleMagneticMove(e, 0.15)}
              style={{
                display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600,
                color: "#635bff", textDecoration: "none", padding: "8px 16px", border: "1px solid #e2e8f0",
                borderRadius: 8, background: "#ffffff", transition: "border-color 0.15s"
              }}
              onMouseEnter={e => (e.currentTarget.style.borderColor = "#cbd5e1")}
              onMouseLeave={e => { handleMagneticLeave(e); e.currentTarget.style.borderColor = "#e2e8f0"; }}
            >
              View All FAQs <ArrowRight size={14} />
            </Link>
          </div>
        </div>
      </section>

      {/* ── ENTERPRISE FOOTER ──────────────────── */}
      <footer className="responsive-hero-section" style={{ background: "#0f172a", color: "#f8fafc", padding: "72px 48px 40px" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div className="responsive-grid-1col" style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr", gap: 48, marginBottom: 56 }}>
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
                <Image src="/main-logo.png" alt="CodeVault" width={48} height={48} style={{ borderRadius: 10 }} />
                <span style={{ fontSize: 18, fontWeight: 800, letterSpacing: "-0.03em", color: "#ffffff" }}>
                  CodeVault
                </span>
              </div>
              <p style={{ fontSize: 14, color: "#94a3b8", lineHeight: 1.6, maxWidth: 300, margin: "0 0 20px" }}>
                Automated LeetCode repository synchronization for software engineers and developers.
              </p>
            </div>

            {[
              { title: "Product", links: [{ label: "Download Extension", href: "/download" }, { label: "Install Guide", href: "/install" }, { label: "Documentation", href: "/docs" }] },
              { title: "Company", links: [{ label: "FAQ", href: "/faq" }, { label: "Contact Support", href: "/contact" }, { label: "Privacy Policy", href: "/privacy" }, { label: "Terms of Service", href: "/terms" }] },
              { title: "Developers", links: [{ label: "GitHub Project", href: "https://github.com" }, { label: "API Reference", href: "/docs" }, { label: "MIT License", href: "https://github.com" }] },
            ].map((col, i) => (
              <div key={i}>
                <h4 style={{ fontSize: 12, fontWeight: 700, color: "#cbd5e1", textTransform: "uppercase", letterSpacing: "0.08em", margin: "0 0 16px" }}>{col.title}</h4>
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10 }}>
                  {col.links.map((link, j) => (
                    <li key={j}>
                      <Link href={link.href} style={{ fontSize: 13, color: "#94a3b8", textDecoration: "none", transition: "color 0.15s" }}
                        onMouseEnter={e => (e.currentTarget.style.color = "#ffffff")}
                        onMouseLeave={e => (e.currentTarget.style.color = "#94a3b8")}>
                        {link.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div style={{ borderTop: "1px solid #1e293b", paddingTop: 28, display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 16 }}>
            <span style={{ fontSize: 13, color: "#64748b" }}>© {new Date().getFullYear()} CodeVault. Open source under the MIT License.</span>
            <div style={{ display: "flex", gap: 24, fontSize: 13, color: "#64748b" }}>
              <Link href="/privacy" style={{ textDecoration: "none", color: "inherit" }}>Privacy Policy</Link>
              <Link href="/terms" style={{ textDecoration: "none", color: "inherit" }}>Terms of Service</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
